version: 1
build:
  binary: "norynthd"
  proto:
    path: "proto"
    third_party_paths:
    - "third_party/proto"
    - "proto_vendor"
validation: sovereign
accounts:
- name: faucet
  coins:
  - 1000000000000ukrn
- name: ecosystem
  coins:
  - 250000000000000ukrn
- name: contributors
  coins:
  - 200000000000000ukrn
- name: builders
  coins:
  - 150000000000000ukrn
- name: treasury
  coins:
  - 150000000000000ukrn
- name: liquidity
  coins:
  - 100000000000000ukrn
- name: community
  coins:
  - 100000000000000ukrn
- name: strategic
  coins:
  - 50000000000000ukrn
client:
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: faucet
  coins:
  - 10000000000ukrn
validators:
- name: alice
  bonded: 50000000000000ukrn
