# This workflow is useful if you want to automate the process of:
#
# a) Creating a new prelease when you push a new tag with a "v" prefix (version).
#
#    This type of prerelease is meant to be used for production: alpha, beta, rc, etc. types of releases.
#    After the prerelease is created, you need to make your changes on the release page at the relevant
#    Github page and publish your release.
#
# b) Creating/updating the "latest" prerelease when you push to your default branch.
#
#    This type of prelease is useful to make your bleeding-edge binaries available to advanced users.
#
# The workflow will not run if there is no tag pushed with a "v" prefix and no change pushed to your
# default branch.
on: push

jobs:
  might_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare Release Variables
        id: vars
        uses: ignite/cli/actions/release/vars@main

      - name: Install C Cross-Compiler for ARM64
        if: ${{ steps.vars.outputs.should_release == 'true' }}
        run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Issue Release Assets (linux/amd64)
        if: ${{ steps.vars.outputs.should_release == 'true' }}
        run: |
          mkdir -p release
          CGO_ENABLED=1 GOOS=linux GOARCH=amd64 \
            go build -o release/norynthd-linux-amd64 \
            -tags "sonic.noasm" \
            -ldflags "-X github.com/cosmos/cosmos-sdk/version.Name=Norynth -X github.com/cosmos/cosmos-sdk/version.AppName=norynthd -X github.com/cosmos/cosmos-sdk/version.Version=${{ steps.vars.outputs.version }} -X github.com/cosmos/cosmos-sdk/version.Commit=${{ github.sha }} -X norynth/cmd/norynthd/cmd.ChainID=norynth" \
            ./cmd/norynthd
        env:
          DO_NOT_TRACK: 1
          GOFLAGS: "-buildvcs=false"

      - name: Issue Release Assets (linux/arm64)
        if: ${{ steps.vars.outputs.should_release == 'true' }}
        run: |
          CC=aarch64-linux-gnu-gcc CGO_ENABLED=1 GOOS=linux GOARCH=arm64 \
            go build -o release/norynthd-linux-arm64 \
            -tags "sonic.noasm" \
            -ldflags "-X github.com/cosmos/cosmos-sdk/version.Name=Norynth -X github.com/cosmos/cosmos-sdk/version.AppName=norynthd -X github.com/cosmos/cosmos-sdk/version.Version=${{ steps.vars.outputs.version }} -X github.com/cosmos/cosmos-sdk/version.Commit=${{ github.sha }} -X norynth/cmd/norynthd/cmd.ChainID=norynth" \
            ./cmd/norynthd
        env:
          DO_NOT_TRACK: 1
          GOFLAGS: "-buildvcs=false"

      - name: Publish the Release
        uses: softprops/action-gh-release@v2
        if: ${{ steps.vars.outputs.should_release == 'true' }}
        with:
          tag_name: ${{ steps.vars.outputs.tag_name }}
          files: release/*
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
